### PR TITLE
Basic c++ code improvements

### PR DESCRIPTION
**Pull request by Frago9876543210**
- function pointers replaced with `decltype(&funcname)`
- cmake min version is 3.0 now
- fixed clang-tidy warns
- knock_test upgraded to python 3
- appveyor uses visual studio 2019

### CODE REVIEW

**Comment by Frago9876543210** [comment]
knock_test.py is still broken for some reason. This should output ping-pong, right?
```
[+] Connecting to port: 1337
[+] Response: b''
```

**Comment by Frago9876543210** [comment]
do we need IAT at all with decltype and casts?

**Comment by Frago9876543210** [comment]
it works!
```
cl /c /GS- /FA knock.cpp
masm_shc.exe knock.asm knock_cleaned_file.asm
ml64 knock_cleaned_file.asm /link /entry:main /section:.text,ERW

.\knock_cleaned_file.exe

py .\knock_test.py --port 1337 --buf="9"
[+] Connecting to port: 1337
[+] Response: b'Y\x00\x00\x00'

py .\knock_test.py --port 1338 --buf="3"
[+] Connecting to port: 1338
[+] Response: b'E\x00\x00\x00'

py .\knock_test.py --port 1339 --buf="5"
[+] Connecting to port: 1339
[+] Response: b'S\x00\x00\x00'
```

**Comment by Frago9876543210** [comment]
would be nice to update paper

**Comment by hasherezade** [comment]
Thank you for your work! 
Upgrading to Python 3 was surely needed, `knock_test.py` was my old script from some other project, and I forgot to change it.
I have some mixed feelings about using `decltype(&funcname)`. Sure it is good for production code, but it is a demo, and I wanted to show how everything works very explicitly, rather than hiding some logic behind autopointers, etc.
But let it be, I will just update the paper, and show both examples.

**Pull request merged**
